version: '3.9'
name: torkan-reserve-stage
services:

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.stage
    container_name: stage-web
    command: sh -c "python manage.py migrate --noinput && 
                    python manage.py collectstatic --noinput && 
                    daphne config.asgi:application --bind 0.0.0.0 --port 8000"
    depends_on:
      - db
      - redis
    env_file:
      - ../env/.env.stage
    volumes:
      - ../static:/code/static
      - ../staticfiles:/code/staticfiles
      - ../media:/code/media
  web_server:
    image: nginx:stable-alpine3.21
    container_name: nginx-stage
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
      - ../staticfiles:/static:ro
      - ../media:/media:ro
      - ../acme-challenge:/var/www/html/.well-known/acme-challenge:ro
      - ../cert:/etc/nginx/ssl:ro
    depends_on:
      - web
  db:
    image: postgres:17-alpine
    container_name: db-stage
    ports:
      - "5432:5432"
    env_file:
      - ../env/.env.stage
    volumes:
      - ../database:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
  redis:
    image: redis:alpine3.22
    container_name: redis-stage
    ports:
      - "6379:6379"